spring:
  datasource:
    url: jdbc:h2:file:/Users/shahriartaj/DukeCourse/java/tenki/db/walletdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always

duke:
  chainId: 1337
  datadir: /Users/shahriartaj/DukeCourse/test-chain-dir
  tenkiAddress: "0xEc10233C905e647fEd29144A4e411c1d7E311264"
  defaultWalletPassword: "costco"